name: CI/CD Pipeline for Next.js - [PRODUCTION]

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build Next.js App
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Docker Build and Push (ARM64 Only)
        id: build-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/mahir213/mahir-portfolio:${{ github.sha }}
            ghcr.io/mahir213/mahir-portfolio:latest

  update-infra:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Infra Repository
        uses: actions/checkout@v4
        with:
          repository: mahir213/infrastructure
          ref: 'main'
          token: ${{ secrets.INFRASTRUCTURE_TOKEN }}
          path: infrastructure

      - name: Verify File Presence
        run: |
          echo "Checking file presence:"
          ls -la infrastructure/portfolio
          cat infrastructure/portfolio/deployment.yml

      - name: Update Deployment Manifest
        run: |
          echo "Updating deployment manifest:"
          # Print the file content before changes
          echo "Before update:"
          cat infrastructure/portfolio/deployment.yml

          # Update the image tag in the deployment manifest
          sed -i "s|image: ghcr.io/portfolio/mahir-portfolio:.*|image: ghcr.io/portfolio/mahir-portfolio:${{ github.sha }}|g" infrastructure/portfolio/deployment.yml

          # Print the file content after changes
          echo "After update:"
          cat infrastructure/portfolio/deployment.yml

      - name: Stage and Commit Changes
        run: |
          cd infrastructure
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add portfolio/deployment.yml
          # Verify the production
          git status
          # Commit and push changes if there are modifications
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update image to version ${{ github.sha }} for arm64"
            git push origin main
          fi
